ALTER TYPE "SyncResourceType" ADD VALUE IF NOT EXISTS 'EXCHANGE_MAILBOXES';
ALTER TYPE "SyncResourceType" ADD VALUE IF NOT EXISTS 'EXCHANGE_MAILBOX_USAGE';
ALTER TYPE "SyncResourceType" ADD VALUE IF NOT EXISTS 'EXCHANGE_ACCEPTED_DOMAINS';
ALTER TYPE "SyncResourceType" ADD VALUE IF NOT EXISTS 'EXCHANGE_MAILBOX_RULES';
