/**
 * Reason vocabularies for the Risky Users normalization layer.
 *
 * THREE SEPARATE VOCABULARIES THAT ARE NEVER SUMMED. A malformed row and an
 * MFA interrupt are different claims about what a result is worth, and one
 * counter for both destroys the distinction:
 *
 *   OutOfScopeReason      the event was understood, and is correctly not
 *                         something the sanctioned detectors act on.
 *                         Does NOT reduce stated coverage. Is still disclosed.
 *   UnknownObservation    we do not recognize the event. Reduces stated
 *                         coverage. Blocks nothing, ever.
 *   UnprocessableReason   we could not read the row at all. Reduces stated
 *                         coverage. Blocks nothing, ever.
 *
 * NO DEFAULT ARM. Every reason's technician-facing label comes from a
 * `Record<Reason, string>` below, so adding a reason without a label is a
 * compile error rather than a fallback string. The predecessor fell back to a
 * label meaning "incomplete collection window", which told technicians to go
 * chase a collection failure that did not exist.
 */

/** Understood, and correctly outside what the three sanctioned rules act on. */
export type OutOfScopeReason =
  | 'NON_INTERACTIVE_SIGN_IN'
  | 'APPLICATION_ACTOR'
  | 'MFA_INTERRUPT'
  | 'KEEP_ME_SIGNED_IN'
  | 'CONDITIONAL_ACCESS_INTERRUPT'
  | 'CONSENT_REQUIRED'
  | 'INSUFFICIENT_SESSION_FOR_SILENT_SIGN_IN';

/** We do not recognize this event. Costs stated coverage and nothing else. */
export type UnknownObservation =
  | 'ERROR_CODE_ABSENT'
  | 'ERROR_CODE_SHAPE_UNRECOGNIZED'
  | 'UNRECOGNIZED_ERROR_CODE'
  | 'AMBIGUOUS_DOCUMENTED_CODE'
  | 'HAWKVIEW_SYNTHETIC_ERROR_CODE'
  | 'SUCCESS_WITH_UNRECOGNIZED_FAILURE_REASON';

/** The row could not be read. Never merged with OutOfScopeReason. */
export type UnprocessableReason =
  | 'RAW_PAYLOAD_MALFORMED'
  | 'SCOPE_MISMATCH'
  | 'SOURCE_UNRECOGNIZED'
  | 'EVENT_ID_ABSENT_OR_MALFORMED'
  | 'EVENT_TIMESTAMP_INVALID'
  | 'INGESTION_TIMESTAMP_INVALID'
  | 'INGESTION_PRECEDES_EVENT'
  | 'INTEGRITY_DISPUTED'
  | 'SUBJECT_ID_ABSENT_OR_MALFORMED'
  | 'SUBJECT_NOT_IN_DIRECTORY'
  | 'SUBJECT_AMBIGUOUS_IN_DIRECTORY'
  | 'SUBJECT_NOT_RESOLVABLE_WITHOUT_GUID'
  | 'APPLICATION_ID_ABSENT_OR_MALFORMED'
  | 'REFERENCE_UNAVAILABLE'
  | 'REFERENCE_BUDGET_EXCEEDED'
  | 'BATCH_LIMIT_EXCEEDED';

/**
 * Technician-facing labels. Exhaustive by construction.
 *
 * Wording rule: an out-of-scope label says what the event WAS. It must never
 * suggest that collection is incomplete or that anything needs chasing.
 */
export const OUT_OF_SCOPE_LABELS: Readonly<Record<OutOfScopeReason, string>> = {
  NON_INTERACTIVE_SIGN_IN: 'Non-interactive sign-in (token refresh or background request), not a credential attempt',
  APPLICATION_ACTOR: 'The actor was an application or service principal, not a person',
  MFA_INTERRUPT: 'Multi-factor authentication was required or enrolment was prompted; not a verdict on the password',
  KEEP_ME_SIGNED_IN: 'Keep-me-signed-in prompt; not a verdict on the password',
  CONDITIONAL_ACCESS_INTERRUPT: 'Blocked or interrupted by a Conditional Access policy; not a verdict on the password',
  CONSENT_REQUIRED: 'Application consent was required; not a credential attempt',
  INSUFFICIENT_SESSION_FOR_SILENT_SIGN_IN: 'Existing session was insufficient for silent sign-in; not a credential attempt',
};

/**
 * Wording rule: an unknown label says HawkView does not recognise the event,
 * and says so as a limit on what we can claim. It must never read as a
 * collection fault, because it is not one.
 */
export const UNKNOWN_LABELS: Readonly<Record<UnknownObservation, string>> = {
  ERROR_CODE_ABSENT: 'The record carried no sign-in result code, so HawkView cannot say what the result was',
  ERROR_CODE_SHAPE_UNRECOGNIZED: 'The sign-in result code was not in a form HawkView reads',
  UNRECOGNIZED_ERROR_CODE: 'HawkView does not recognise this sign-in result code',
  AMBIGUOUS_DOCUMENTED_CODE: 'This result code has more than one documented meaning and HawkView will not guess between them',
  HAWKVIEW_SYNTHETIC_ERROR_CODE: 'Result code was generated by HawkView’s own fallback path, not by Microsoft',
  SUCCESS_WITH_UNRECOGNIZED_FAILURE_REASON: 'Reported as a success but carried an unrecognised failure reason, so HawkView will not call it a success',
};

/**
 * Wording rule: an unprocessable label describes the row defect, and is the
 * ONLY vocabulary that may point at collection or data quality.
 */
export const UNPROCESSABLE_LABELS: Readonly<Record<UnprocessableReason, string>> = {
  RAW_PAYLOAD_MALFORMED: 'The stored record was not a readable object',
  SCOPE_MISMATCH: 'The record belonged to a different organisation or customer tenant',
  SOURCE_UNRECOGNIZED: 'The record did not identify which collection feed produced it',
  EVENT_ID_ABSENT_OR_MALFORMED: 'The record carried no usable event identifier',
  EVENT_TIMESTAMP_INVALID: 'The record carried no usable event timestamp',
  INGESTION_TIMESTAMP_INVALID: 'The row carried no usable ingestion timestamp',
  INGESTION_PRECEDES_EVENT: 'The row was recorded as ingested before the event it describes',
  INTEGRITY_DISPUTED: 'Collection flagged this record’s integrity as disputed',
  SUBJECT_ID_ABSENT_OR_MALFORMED: 'The record carried no directory object id for the signing-in user',
  SUBJECT_NOT_IN_DIRECTORY: 'The directory object id on the record is not present in the collected directory',
  SUBJECT_AMBIGUOUS_IN_DIRECTORY: 'The directory object id on the record matched more than one directory record',
  SUBJECT_NOT_RESOLVABLE_WITHOUT_GUID: 'This feed identifies users only by name, and HawkView binds users by directory object id only',
  APPLICATION_ID_ABSENT_OR_MALFORMED: 'The record carried no usable application id',
  REFERENCE_UNAVAILABLE: 'A protected reference for the user or application could not be produced',
  REFERENCE_BUDGET_EXCEEDED: 'This evaluation reached its limit on distinct protected references',
  BATCH_LIMIT_EXCEEDED: 'This evaluation reached its per-run row limit before reaching this row',
};

/**
 * Zero-filled counters keyed by every reason in a vocabulary.
 *
 * Deriving the keys from the label map is what keeps counters and labels from
 * drifting: a reason that exists has a label and a counter, or this module
 * does not compile.
 */
export function zeroCounts<Key extends string>(labels: Readonly<Record<Key, string>>): Record<Key, number> {
  return Object.fromEntries(Object.keys(labels).map(key => [key, 0])) as Record<Key, number>;
}

/** Exhaustiveness guard. Reachable only if a union gained a member without a branch. */
export function unreachable(value: never): never {
  throw new Error(`RISKY_USERS_NORMALIZATION_UNREACHABLE:${String(value)}`);
}

export function describeOutOfScope(reason: OutOfScopeReason): string {
  return OUT_OF_SCOPE_LABELS[reason];
}
export function describeUnknown(observation: UnknownObservation): string {
  return UNKNOWN_LABELS[observation];
}
export function describeUnprocessable(reason: UnprocessableReason): string {
  return UNPROCESSABLE_LABELS[reason];
}
