import assert from 'node:assert/strict'
import test from 'node:test'
import { SyncResourceType } from '../generated/prisma/enums.js'
import {
  SERVICE_COLLECTOR_REGISTRY,
  deriveTenantSyncFreshness,
  type TenantSyncFreshness,
} from './service-sync-freshness.js'

/** Every collector has EXACTLY ONE owning service.
 *
 * THE REFERENCE LIST COMES FROM THE OTHER SIDE OF THE BOUNDARY. `SyncResourceType`
 * is generated by Prisma from `schema.prisma`; the registry is hand-written. A
 * check built from the registry's own contents would agree with it by
 * construction and could never find the defect it exists to find — which is
 * exactly how three collectors came to belong to no service while every test
 * passed.
 *
 * The "at least one" half is also enforced at compile time by
 * `EveryCollectorHasAnOwningService`, and that check was verified to discriminate:
 * removing a collector from the registry fails `tsc` naming it. This file covers
 * the half types cannot do — counting, so that a collector owned TWICE is caught
 * too — and the behaviour that makes it matter.
 */

const collectorsOf = (service: (typeof SERVICE_COLLECTOR_REGISTRY)[number]) => service.collectors

const now = new Date('2026-08-13T14:02:00.000Z')
const success = (resourceType: string, at = '2026-08-13T14:00:00.000Z') => ({
  resourceType, status: 'SUCCEEDED', lastAttemptAt: new Date(at), lastSuccessfulAt: new Date(at),
  lastErrorCode: null, lastErrorMessage: null, consecutiveFailures: 0,
})
const failed = (resourceType: string) => ({
  resourceType, status: 'FAILED', lastAttemptAt: now, lastSuccessfulAt: null,
  lastErrorCode: '500', lastErrorMessage: 'Microsoft API error', consecutiveFailures: 1,
})

/** Which services mention `collector` anywhere in their reported failures. */
function servicesReporting(freshness: TenantSyncFreshness, collector: string): string[] {
  return Object.entries(freshness.services)
    .filter(([, service]) => service.partialFailures.some((failure) => failure.collector === collector))
    .map(([key]) => key)
}

test('EVERY collector belongs to exactly one service', () => {
  const everyCollector = Object.values(SyncResourceType)
  const owned = SERVICE_COLLECTOR_REGISTRY.flatMap(collectorsOf)

  // POSITIVE CONTROL FIRST: both lists were actually read. Without this the
  // comparisons below pass on two empty arrays, which is the vacuity that has
  // bitten this codebase repeatedly.
  assert.ok(everyCollector.length > 20, 'the Prisma enum was not read')
  assert.ok(owned.length > 20, 'the registry was not read')

  const unowned = everyCollector.filter((collector) => !owned.includes(collector))
  assert.deepEqual(unowned, [],
    'a collector with no owning service contributes to nothing and is invisible, not mislabelled')

  const seen = new Map<string, number>()
  for (const collector of owned) seen.set(collector, (seen.get(collector) ?? 0) + 1)
  const ownedTwice = [...seen].filter(([, count]) => count > 1).map(([collector]) => collector)
  assert.deepEqual(ownedTwice, [],
    'a collector owned twice is double-counted in service totals')

  // And nothing in the registry has fallen out of the schema. The type prevents
  // this now; the assertion says so out loud for a reader.
  const notACollector = owned.filter((collector) => !everyCollector.includes(collector))
  assert.deepEqual(notACollector, [])
})

test('the three collectors that belonged to nothing now reach a service', () => {
  // Named individually rather than only covered by the sweep above, because
  // these three are the defect: SECURE_SCORES failing on all five tenants for
  // seventeen days could not surface on any screen.
  const owner = (collector: string) =>
    SERVICE_COLLECTOR_REGISTRY.find((service) => (collectorsOf(service) as readonly string[]).includes(collector))?.key

  assert.equal(owner('SECURE_SCORES'), 'entraId')
  assert.equal(owner('ORGANIZATION_CONFIGURATION'), 'office365')
  assert.equal(owner('EXCHANGE_MAILBOX_CONFIGURATION'), 'exchange')
})

test('A FAILING SECURE SCORES COLLECTOR NOW REACHES A SCREEN', () => {
  // The behavioural proof, and the reason any of this matters. Previously this
  // collector was in no service, so `deriveTenantSyncFreshness` — which iterates
  // the registry, not the enum — never looked at its state. The failure existed
  // in the database and appeared nowhere.
  const entraCollectors = SERVICE_COLLECTOR_REGISTRY.find((service) => service.key === 'entraId')!.collectors
  const states = entraCollectors.map((collector) =>
    collector === 'SECURE_SCORES' ? failed(collector) : success(collector))

  const freshness = deriveTenantSyncFreshness(states, now)
  assert.equal(freshness.services.entraId.status, 'PARTIAL', 'the service must report the failure')
  assert.equal(freshness.services.entraId.failedCollectors, 1)
  assert.ok(
    freshness.services.entraId.partialFailures.some((failure) => failure.collector === 'SECURE_SCORES'),
    'and must name the collector that failed')

  // Exactly one service reports it — the behavioural form of single ownership.
  assert.deepEqual(servicesReporting(freshness, 'SECURE_SCORES'), ['entraId'])

  // POSITIVE CONTROL: with every collector succeeding, no service reports it. So
  // the assertions above are about the failure rather than a collector that is
  // always listed.
  const healthy = deriveTenantSyncFreshness(entraCollectors.map((collector) => success(collector)), now)
  assert.equal(healthy.services.entraId.status, 'SUCCESS')
  assert.deepEqual(servicesReporting(healthy, 'SECURE_SCORES'), [])
})

test('the other two reach a screen as well', () => {
  for (const [collector, key] of [
    ['ORGANIZATION_CONFIGURATION', 'office365'],
    ['EXCHANGE_MAILBOX_CONFIGURATION', 'exchange'],
  ] as const) {
    const collectors = SERVICE_COLLECTOR_REGISTRY.find((service) => service.key === key)!.collectors
    const states = collectors.map((entry) => (entry === collector ? failed(entry) : success(entry)))
    const freshness = deriveTenantSyncFreshness(states, now)
    assert.deepEqual(servicesReporting(freshness, collector), [key], `${collector} must reach ${key}`)
  }
})

test('an excluded collector is removed from the denominator, not counted as a failure', () => {
  // How "we are not allowed to ask" is handled today: the CALLER excludes the
  // collector before derivation (tenants.service.ts passes the NOT_LICENSED and
  // UNSUPPORTED resource types), so it leaves the expected count rather than
  // failing it. Asserted here because the new collectors change those counts and
  // a reader should see the mechanism.
  const collectors = SERVICE_COLLECTOR_REGISTRY.find((service) => service.key === 'exchange')!.collectors
  const present = collectors.filter((entry) => entry !== 'EXCHANGE_MAILBOX_CONFIGURATION')

  const excluded = deriveTenantSyncFreshness(
    present.map((entry) => success(entry)), now, ['EXCHANGE_MAILBOX_CONFIGURATION'])
  assert.equal(excluded.services.exchange.status, 'SUCCESS')
  assert.equal(excluded.services.exchange.expectedCollectors, present.length)

  // POSITIVE CONTROL: without the exclusion the same states report the missing
  // collector, so the pass above is the exclusion and not an inert count.
  const notExcluded = deriveTenantSyncFreshness(present.map((entry) => success(entry)), now)
  assert.notEqual(notExcluded.services.exchange.status, 'SUCCESS')
  assert.deepEqual(servicesReporting(notExcluded, 'EXCHANGE_MAILBOX_CONFIGURATION'), ['exchange'])
})
